version: 2

models:
  - name: stg_orders
    description: "Table des commandes avec l'ID du client"
    columns :
      - name : order_id
        description : "ID de la commande"
        tests :
          - unique
          - not_null

sources:
  - name : local_bike
    schema : local_bike
    tables :
      - name: brands
      - name: categories
      - name: customers
      - name: order_items
      - name: orders
      - name: products
      - name: staffs
      - name: stocks
      - name: stores


