version: 2

models:
  - name: stg_orders
    description: "Table de staging pour ne récupérer que les colonnes et lignes essentielles. Table partitionnée sur order_date"
    columns :
      - name : order_id
        description : "ID unique de la commande que nous testions, clé primaire. permet de récupérer les données de la table order_items"
        tests :
          - unique
          - not_null
      - name : order_date
        description: "partionnement sur cette colonne"

  - name : stg_order_items
    description: "Table de staging pour ne récupérer que les colonnes et lignes essentielles. Permet de faire la jointure entre stg_orders et stg_products"
    columns:
      - name: order_id
      - name : product_id
      - name : quantity
      - name : list_price


sources:
  - name : local_bike
    schema : local_bike
    tables :
      - name: brands
      - name: categories
      - name: customers
      - name: order_items
      - name: orders
      - name: products
      - name: staffs
      - name: stocks
      - name: stores